// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: example/example.proto

package example

import (
	_ "github.com/lemonkingstar/spider/cmd/protoc-gen-gotags/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Example struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty" graphql:"withNewTags,optional"`
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty" graphql:"withNewTags,optional" xml:"multi,omitempty"`
	ReplaceDefault  *string                `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3,oneof" json:"replacePrevious"`
	// Types that are valid to be assigned to OneOf:
	//
	//	*Example_A
	//	*Example_BJk
	OneOf         isExample_OneOf `protobuf_oneof:"one_of" graphql:"withNewTags,optional" json:"withNewTags"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_example_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *Example) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *Example) GetReplaceDefault() string {
	if x != nil && x.ReplaceDefault != nil {
		return *x.ReplaceDefault
	}
	return ""
}

func (x *Example) GetOneOf() isExample_OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *Example) GetA() string {
	if x != nil {
		if x, ok := x.OneOf.(*Example_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *Example) GetBJk() int32 {
	if x != nil {
		if x, ok := x.OneOf.(*Example_BJk); ok {
			return x.BJk
		}
	}
	return 0
}

type isExample_OneOf interface {
	isExample_OneOf()
}

type Example_A struct {
	A string `protobuf:"bytes,5,opt,name=a,proto3,oneof" json:"A"`
}

type Example_BJk struct {
	BJk int32 `protobuf:"varint,6,opt,name=b_jk,json=bJk,proto3,oneof" json:"b_Jk"`
}

func (*Example_A) isExample_OneOf() {}

func (*Example_BJk) isExample_OneOf() {}

type SecondMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty" graphql:"withNewTags,optional"`
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty" graphql:"withNewTags,optional" xml:"multi,omitempty"`
	ReplaceDefault  string                 `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replacePrevious"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecondMessage) Reset() {
	*x = SecondMessage{}
	mi := &file_example_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecondMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondMessage) ProtoMessage() {}

func (x *SecondMessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondMessage.ProtoReflect.Descriptor instead.
func (*SecondMessage) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{1}
}

func (x *SecondMessage) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *SecondMessage) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *SecondMessage) GetReplaceDefault() string {
	if x != nil {
		return x.ReplaceDefault
	}
	return ""
}

type ThirdExample struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	InnerExample  *ThirdExample_InnerExample `protobuf:"bytes,1,opt,name=inner_example,json=innerExample,proto3" json:"inner"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample) Reset() {
	*x = ThirdExample{}
	mi := &file_example_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample) ProtoMessage() {}

func (x *ThirdExample) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample.ProtoReflect.Descriptor instead.
func (*ThirdExample) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{2}
}

func (x *ThirdExample) GetInnerExample() *ThirdExample_InnerExample {
	if x != nil {
		return x.InnerExample
	}
	return nil
}

type FourthExample struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags"`
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,optional" graphql:"withNewTags,optional"`
	ReplaceDefault  *string                `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3,oneof" json:"replacePrevious"`
	// Types that are valid to be assigned to OneOf:
	//
	//	*FourthExample_A
	//	*FourthExample_BJk
	OneOf         isFourthExample_OneOf `protobuf_oneof:"one_of"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FourthExample) Reset() {
	*x = FourthExample{}
	mi := &file_example_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FourthExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FourthExample) ProtoMessage() {}

func (x *FourthExample) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FourthExample.ProtoReflect.Descriptor instead.
func (*FourthExample) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{3}
}

func (x *FourthExample) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *FourthExample) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *FourthExample) GetReplaceDefault() string {
	if x != nil && x.ReplaceDefault != nil {
		return *x.ReplaceDefault
	}
	return ""
}

func (x *FourthExample) GetOneOf() isFourthExample_OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *FourthExample) GetA() string {
	if x != nil {
		if x, ok := x.OneOf.(*FourthExample_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *FourthExample) GetBJk() int32 {
	if x != nil {
		if x, ok := x.OneOf.(*FourthExample_BJk); ok {
			return x.BJk
		}
	}
	return 0
}

type isFourthExample_OneOf interface {
	isFourthExample_OneOf()
}

type FourthExample_A struct {
	A string `protobuf:"bytes,5,opt,name=a,proto3,oneof"`
}

type FourthExample_BJk struct {
	BJk int32 `protobuf:"varint,6,opt,name=b_jk,json=bJk,proto3,oneof"`
}

func (*FourthExample_A) isFourthExample_OneOf() {}

func (*FourthExample_BJk) isFourthExample_OneOf() {}

type ThirdExample_InnerExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"yes"`
	Yes           int32                  `protobuf:"varint,2,opt,name=yes,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample_InnerExample) Reset() {
	*x = ThirdExample_InnerExample{}
	mi := &file_example_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample_InnerExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample_InnerExample) ProtoMessage() {}

func (x *ThirdExample_InnerExample) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample_InnerExample.ProtoReflect.Descriptor instead.
func (*ThirdExample_InnerExample) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ThirdExample_InnerExample) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThirdExample_InnerExample) GetYes() int32 {
	if x != nil {
		return x.Yes
	}
	return 0
}

var File_example_example_proto protoreflect.FileDescriptor

const file_example_example_proto_rawDesc = "" +
	"\n" +
	"\x15example/example.proto\x12\aexample\x1a\x13tagger/tagger.proto\"\x98\x03\n" +
	"\aExample\x12E\n" +
	"\rwith_new_tags\x18\x01 \x01(\tB!\x9a\xa8\x86\a\x1cgraphql:withNewTags,optionalR\vwithNewTags\x12e\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tB9\x9a\xa8\x86\a\x1cgraphql:withNewTags,optional\x9a\xa8\x86\a\x13xml:multi,omitemptyR\x0fwithNewMultiple\x12G\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x19\x9a\xa8\x86\a\x14json:replacePreviousH\x01R\x0ereplaceDefault\x88\x01\x01\x12\x1b\n" +
	"\x01a\x18\x05 \x01(\tB\v\x9a\xa8\x86\a\x06json:AH\x00R\x01a\x12#\n" +
	"\x04b_jk\x18\x06 \x01(\x05B\x0e\x9a\xa8\x86\a\tjson:b_JkH\x00R\x03bJkB@\n" +
	"\x06one_of\x126\x9a\xa8\x86\a\x1cgraphql:withNewTags,optional\x9a\xa8\x86\a\x10json:withNewTagsB\x12\n" +
	"\x10_replace_default\"\x81\x02\n" +
	"\rSecondMessage\x12E\n" +
	"\rwith_new_tags\x18\x01 \x01(\tB!\x9a\xa8\x86\a\x1cgraphql:withNewTags,optionalR\vwithNewTags\x12e\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tB9\x9a\xa8\x86\a\x1cgraphql:withNewTags,optional\x9a\xa8\x86\a\x13xml:multi,omitemptyR\x0fwithNewMultiple\x12B\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x19\x9a\xa8\x86\a\x14json:replacePreviousR\x0ereplaceDefault\"\xb7\x01\n" +
	"\fThirdExample\x12X\n" +
	"\rinner_example\x18\x01 \x01(\v2\".example.ThirdExample.InnerExampleB\x0f\x9a\xa8\x86\a\n" +
	"json:innerR\finnerExample\x1aM\n" +
	"\fInnerExample\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\tB\r\x9a\xa8\x86\a\bjson:yesR\x02id\x12\x1e\n" +
	"\x03yes\x18\x02 \x01(\x05B\f\x9a\xa8\x86\a\ajson:idR\x03yes\"\xb9\x02\n" +
	"\rFourthExample\x12\"\n" +
	"\rwith_new_tags\x18\x01 \x01(\tR\vwithNewTags\x12q\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tBE\x9a\xa8\x86\a\x1cgraphql:withNewTags,optional\x9a\xa8\x86\a\x1fjson:with_new_multiple,optionalR\x0fwithNewMultiple\x12G\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x19\x9a\xa8\x86\a\x14json:replacePreviousH\x01R\x0ereplaceDefault\x88\x01\x01\x12\x0e\n" +
	"\x01a\x18\x05 \x01(\tH\x00R\x01a\x12\x13\n" +
	"\x04b_jk\x18\x06 \x01(\x05H\x00R\x03bJk:\x05\x98\xa8\x86\a\x01B\b\n" +
	"\x06one_ofB\x12\n" +
	"\x10_replace_defaultBGZEgithub.com/lemonkingstar/spider/cmd/protoc-gen-gotags/example;exampleb\x06proto3"

var (
	file_example_example_proto_rawDescOnce sync.Once
	file_example_example_proto_rawDescData []byte
)

func file_example_example_proto_rawDescGZIP() []byte {
	file_example_example_proto_rawDescOnce.Do(func() {
		file_example_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_example_proto_rawDesc), len(file_example_example_proto_rawDesc)))
	})
	return file_example_example_proto_rawDescData
}

var file_example_example_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_example_example_proto_goTypes = []any{
	(*Example)(nil),                   // 0: example.Example
	(*SecondMessage)(nil),             // 1: example.SecondMessage
	(*ThirdExample)(nil),              // 2: example.ThirdExample
	(*FourthExample)(nil),             // 3: example.FourthExample
	(*ThirdExample_InnerExample)(nil), // 4: example.ThirdExample.InnerExample
}
var file_example_example_proto_depIdxs = []int32{
	4, // 0: example.ThirdExample.inner_example:type_name -> example.ThirdExample.InnerExample
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_example_proto_init() }
func file_example_example_proto_init() {
	if File_example_example_proto != nil {
		return
	}
	file_example_example_proto_msgTypes[0].OneofWrappers = []any{
		(*Example_A)(nil),
		(*Example_BJk)(nil),
	}
	file_example_example_proto_msgTypes[3].OneofWrappers = []any{
		(*FourthExample_A)(nil),
		(*FourthExample_BJk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_example_proto_rawDesc), len(file_example_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_example_proto_goTypes,
		DependencyIndexes: file_example_example_proto_depIdxs,
		MessageInfos:      file_example_example_proto_msgTypes,
	}.Build()
	File_example_example_proto = out.File
	file_example_example_proto_goTypes = nil
	file_example_example_proto_depIdxs = nil
}
