// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: tagger.proto

package tagger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_tagger_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1847939,
		Name:          "spider.tagger.disable_omitempty",
		Tag:           "varint,1847939,opt,name=disable_omitempty",
		Filename:      "tagger.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         1847939,
		Name:          "spider.tagger.tags",
		Tag:           "bytes,1847939,rep,name=tags",
		Filename:      "tagger.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         1847939,
		Name:          "spider.tagger.oneof_tags",
		Tag:           "bytes,1847939,rep,name=oneof_tags",
		Filename:      "tagger.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Disable json omitempty.
	//
	// optional bool disable_omitempty = 1847939;
	E_DisableOmitempty = &file_tagger_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Multiple Tags can be specified.
	//
	// repeated string tags = 1847939;
	E_Tags = &file_tagger_proto_extTypes[1]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// Multiple Tags can be specified.
	//
	// repeated string oneof_tags = 1847939;
	E_OneofTags = &file_tagger_proto_extTypes[2]
)

var File_tagger_proto protoreflect.FileDescriptor

const file_tagger_proto_rawDesc = "" +
	"\n" +
	"\ftagger.proto\x12\rspider.tagger\x1a google/protobuf/descriptor.proto:N\n" +
	"\x11disable_omitempty\x12\x1f.google.protobuf.MessageOptions\x18\x83\xe5p \x01(\bR\x10disableOmitempty:3\n" +
	"\x04tags\x12\x1d.google.protobuf.FieldOptions\x18\x83\xe5p \x03(\tR\x04tags:>\n" +
	"\n" +
	"oneof_tags\x12\x1d.google.protobuf.OneofOptions\x18\x83\xe5p \x03(\tR\toneofTagsBEZCgithub.com/lemonkingstar/spider/cmd/protoc-gen-gotags/tagger;taggerb\x06proto3"

var file_tagger_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),   // 2: google.protobuf.OneofOptions
}
var file_tagger_proto_depIdxs = []int32{
	0, // 0: spider.tagger.disable_omitempty:extendee -> google.protobuf.MessageOptions
	1, // 1: spider.tagger.tags:extendee -> google.protobuf.FieldOptions
	2, // 2: spider.tagger.oneof_tags:extendee -> google.protobuf.OneofOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tagger_proto_init() }
func file_tagger_proto_init() {
	if File_tagger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tagger_proto_rawDesc), len(file_tagger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_tagger_proto_goTypes,
		DependencyIndexes: file_tagger_proto_depIdxs,
		ExtensionInfos:    file_tagger_proto_extTypes,
	}.Build()
	File_tagger_proto = out.File
	file_tagger_proto_goTypes = nil
	file_tagger_proto_depIdxs = nil
}
